[package]
name = "re2line"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
binrw = "0.14.1"
derive_more = { version = "2.0.1", features = ["full"] }
eframe = "0.31.1"
egui = "0.31.1"
epaint = "0.31.1"
rfd = "0.15.3"